apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespace.yaml
  - ../../configmap.yaml
  - kind-secrets.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - minio-init-job.yaml
  - ../../api-deployment.yaml
  - ../../api-service.yaml
  - ../../worker-deployment.yaml
  - ../../reconciler-deployment.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

patches:
  - path: patches/configmap-kind.yaml
  - path: patches/api-kind.yaml
  - path: patches/worker-kind.yaml
  - path: patches/reconciler-kind.yaml
