apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processing-frontend
  namespace: video-processing
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
