apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processing-worker
  namespace: video-processing
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: worker
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
