apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processing-reconciler
  namespace: video-processing
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: reconciler
          image: ghcr.io/richinmrudul/distributed-video-processing-infra-reconciler:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
