apiVersion: v1
kind: Service
metadata:
  name: video-processing-frontend
  namespace: video-processing
  labels:
    app.kubernetes.io/name: video-processing
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: video-processing
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
